---
services:
#RADARR#
#RADARR#
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/thomascline/Docker/Arr/radarr/data:/config
      - /mnt/data/movies:/movies #optional
      - /home/thomascline/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
