---
services:
#LIDARR#
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/thomascline/Docker/Arr/lidarr/config:/config
      - /mnt/data/music:/music #optional
      - /home/thomascline/Downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
